baseURL = "https://example.com/"
languageCode = "en-us"
title = "Matthew Baldeosingh"
theme = "hugo-resume"
publishDir = "dist"

[params]
    firstName = "Matthew"
    lastName = "Baldeosingh"
    address = "Brooklyn, NY"
    phone = "1-347-867-0060"
    profileImage = "img/headshot.jpg"
    email = "matthewbaldeosingh451@gmail.com"
    description = "Computer Science and Economics double major."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = false
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true
    # showResume = true //create a function that calls Resume

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/baldeosingh"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/baldeosinghm/"


[params.google.analytics]
    trackerID = "XX-123446-01"
